### ISSUE TITLE
entql: uuid support

### ISSUE THREAD

**Issue by BrentChesny** [facebook/ent#1002]
Hello there!

We're currently trying to integrate Ent into our project while making use of the new privacy layer. We want to implement a rule that is similar to the FilterTenantRule in the privacytenant example. This rule uses the Filter interface provided by the entql extension. However, when enabling the entql extension in our project, it turned out that it fails on UUID fields. The generated `entql.go` file is invalid since the UUID type gets filled in as `[16]byte` in the template.

```
// WhereID applies the entql [16]byte predicate on the id field.
func (f *OrganisationFilter) WhereID(p entql.[16]byteP) {
	f.Where(p.Field(organisation.FieldID))
}
```

It would seem to me that entql/types.go needs to be extended with the proper types for UUID/[16]byte fields.

Would be great if anyone could give some advice on how to proceed/work around this, since this is quite blocking to us at the moment.

**Comment by BrentChesny** [comment]
I realise that the entql extension is still experimental, but creating a Filtering privacy rule seems to rely on it.

**Comment by a8m** [comment]
Hey @BrentChesny and thanks for reporting this.

I’ll give it a look in the upcoming hour and update you.

**Comment by BrentChesny** [comment]
@a8m Made a pull request that I believe fixes the issue. Let me know if I missed something :)

**Comment by a8m** [comment]
Wow, that was fast @BrentChesny, but I actually came up with a little bit different fix for this in #1004 (I saw yours after I created mine).

I think `UUID` fields should be type `driver.Valuer` because this is what we accept in the `schema/field` package (`field.UUID`), and we don't care about the underlying Go type. WDYT?

I know that the popular solutions outside for UUID types use `[16]byte`, but I'm afraid that someone uses a different type for it, and it won't support this.

Anyway, let me know what do you think, and if you'd like to change your PR and we can abandon #1004.

**Comment by BrentChesny** [comment]
> I think UUID fields should be type driver.Valuer because this is what we accept in the schema/field package (field.UUID), and we don't care about the underlying Go type. WDYT?

I think yours is indeed the better solution. I have just one remark on #1004. Other than that it looks good, and we can abandon my PR.

**Comment by a8m** [comment]
Fixed with https://github.com/facebook/ent/pull/1004.

Thanks for your contribution @BrentChesny, it's really appreciated.

**Comment by BrentChesny** [comment]
Thanks @a8m for your quick response to this! 🙏🏻

**Comment by a8m** [comment]
Great, closing! Feel free to reopen if you still have troubles with it.
