### ISSUE TITLE
LastInsertID method for non-int-ID nodes

### ISSUE THREAD

**Issue by aight8** [facebook/ent#1103]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Cant convert non-int ID field (like string, or custom type) to desired value. 
https://github.com/facebook/ent/blob/master/dialect/sql/sqlgraph/graph.go#L1182-L1200

## Expected Behavior 🤔

lastInsertID should respect any type.

**Comment by cliedeman** [comment]
@aight8 Which database are you using?

for mysql and sqlite the limitation seems to be on the database/sql [result](https://golang.org/pkg/database/sql/#Result) type

I have implemented a fix for postgres in #1104

**Comment by aight8** [comment]
Yes I'm using postgres. Your PR solves exactly what I meant. thanks!

**Comment by a8m** [comment]
Hey @aight8,

This is a PostgreSQL thing, and other dialects don't really support this - but I don't mind adding this. Also, I expect that the configuration of the generated ID value was created by other tool (or manually), because ent supports only auto_increment ids for such configuration. 

Thanks a lot @cliedeman for sending this patch really quickly. I'll review this.

**Comment by a8m** [comment]
Closing with #1104

**Comment by a8m** [comment]
Closed with #1104
