### ISSUE TITLE
Naming convention for multi-word fields / edges 

### ISSUE THREAD

**Issue by adayNU** [facebook/ent#1107]
Is there a standard naming convention for fields and/or edges which are more than one word?

Just wondering since I _believe_ its standard to use `snake_case` for things like database columns, but Go uses `camelCase`. My hunch is to use `snake_case` but couldn't find that explicitly called out anywhere.

**Comment by notzheng** [comment]
I hope this can help you.


[](https://github.com/facebook/ent/issues/1069)

**Comment by a8m** [comment]
Hey @adayNU! 

> Is there a standard naming convention for fields and/or edges which are more than one word?

Yes, we use `snake_case` for both fields and edges, and ent automatically "pascalize" them in Go code when it's needed (e.g. struct fields or methods). The database columns (and struct tags) will be the same as you wrote the fields/edge in the schema unless stated otherwise (e.g. manually configured the column and the struct-tag using the `StorageKey` and `StructTag` options). 

Closing, but please feel free to contribute a change for adding the convention section to the [schema fields page](https://entgo.io/docs/schema-fields/). The change can be added [here](https://entgo.io/docs/schema-fields/). 

Thanks 😃
