### ISSUE TITLE
Invalid type for ScanValues and Assign

### ISSUE THREAD

**Issue by napei** [facebook/ent#1115]
- [ ] The issue is present in the latest release. 
    - Present in master branch
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

After checking out master while working on a PR, the changes in da345715608ff2d89a75b0b2ce8852a60df9424f appear to break my current repo when running `go generate ./...`

![image](https://user-images.githubusercontent.com/8946502/103450734-79023200-4d0e-11eb-8c7f-19b7810b36ad.png)

It appears that it's not being regenerated.

I'll also point out that 2 of my schemas have hooks, which had errors at one point after running codegen that resulted in the above errors, but that has since gone. Not sure if related or not.

**Comment by a8m** [comment]
Hey @napei,

> I'll also point out that 2 of my schemas have hooks, which had errors at one point after runnin codegen that resulted in the above errors, but that has since gone. Not sure if related or not.

Code can't be generated because you have hooks in your schema. I'm pretty sure the [`schema/snapshot`](https://entgo.io/docs/feature-flags/#auto-solve-merge-conflicts) feature-flag should solve the problem, and I planned to add a workaround for this in the release note.

Can you try please to run the following commands and report if that solves the issue:
1. Add the `--feature schema/snapshot` option to your codegen parameters and re-run codegen
2. Update to latest master
3. Run code again

**Comment by napei** [comment]
> * Add the `--feature schema/snapshot` option to your codegen parameters and re-run codegen
> * Update to latest master
> * Run code again

That works! Code has regenerated

**Comment by a8m** [comment]
Great, thanks 😍
