### ISSUE TITLE
question: What is the recommended way to clean up a bad/broken generated Entity ?

### ISSUE THREAD

**Issue by alkanna** [facebook/ent#1236]
Let's say I have not yet run the migration against the database.
I have not committed any of my work for a while (my bad ?).
I generate an entity named Config. All is well, I define my fields, my edges... I generate the code... Then I fire up my program, and the compilation fails because ent is already using a Config struct of its own!

Now I don't mind changing the name of this entity to something else, and I understand that there is probably a real fix to be made here in ent's code generation (such as maybe aliasing the import of generated entities ?), but how do I "undo" that ?

What I ended up doing was:

- back-up my schemas
- delete the ent folder
- run ent init for each of my schema
- restored my backed-up schemas except for the problematic Config entity
- run go generate ./ent

Is there a more idiomatic way to do all of that ? I understand code generation is a tricky business though. I haven't looked at the internals of this package, but I expect it should already prevent creating entities with forbidden keywords, such as built-in types. Maybe this should include some of this package's types ?

Thanks

**Comment by a8m** [comment]
Hey @alkanna and thanks for raising up this issue.

Regarding the `Config` naming problem - an identical issue was opened a few days ago (https://github.com/facebook/ent/issues/1225). It should be solved in the upcoming days, I'm just giving new contributors a chance to submit a patch because the fix is simple. We usually don't generate new assets if there's a problem with the schema, but in this case we missed it.

Regarding your first question - currently, `ent` CLI doesn't support this. I thought about adding this functionality a long time ago, but ended up with using my custom script for this. I uploaded it to GitHub and you can install it from `github.com/a8m/entclean`.

Why I don't want to add it to the default CLI? because in the upcoming future, I'm going to support ent/schema versioning, and this functionality will be there by default (more details in the issue tracker soon).

**Comment by napei** [comment]
> Regarding the `Config` naming problem

My bad, I missed this in #1110, see a fix for this in #1239

**Comment by alkanna** [comment]
Was about to submit a PR for this :)

**Comment by alkanna** [comment]
I see that your PR has been merged so I'll close this. Thanks!
