### ISSUE TITLE
proposal: Generated Data Loaders

### ISSUE THREAD

**Issue by BitPhinix** [facebook/ent#357]
It would be nice if ent would generate some sort of dataloaders / context-specific caching and batching layer like https://github.com/vektah/dataloaden. That would simplify using ent in GraphQL APIs a lot by removing the need to build an extra abstraction layer over "simple" database operations.

**Comment by a8m** [comment]
Hey @BitPhinix, that's a great idea.

As I commented [here](https://github.com/facebookincubator/ent/issues/356#issuecomment-589646351), we already have some gqlgen integration that we want to OSS and it's ongoing (We actually tackled this problem with field-collections and eager-loading).

I'll move this issue to the new repository once it's out.

**Comment by BitPhinix** [comment]
That would be awesome - and is exactly what I've been looking for. When are you planning to release it? I would love to use it asap. Thanks for this awesome project!

**Comment by pbrazdil** [comment]
Any update on OSS-ing gqlgen integration?

**Comment by ImKcat** [comment]
Still waiting for the gqlgen integration release

**Comment by jufemaiz** [comment]
QQ on this – is the proposal to adopt Relay node/connection approach?

**Comment by a8m** [comment]
Hey guys, the GraphQL integration was open-sourced along with a (WIP) doc - [entgo.io/docs/graphql](https://entgo.io/docs/graphql/). 

Closing, but please go over it and open an issue if there's a specific feature that's miss there. Thanks

**Comment by Sytten** [comment]
I took a look at the integration but I am still unsure if the original question was answered. I tried to run the todo example to see if it was using some kind of batching to avoid the N+1 issue and I don't think it does? I think it either misses some documentation on the topic or it is not done yet, can you comment on that @a8m.
It was actually one of the first things I check for new server implementations.

I think the best would be to create a complete/complex example of GraphQL + ent that has multi-tenant and deeply nested loading and permission checks with the privacy feature. Currently I have a hard time judging if ent + entgql is production ready.

**Comment by a8m** [comment]
Hey @Sytten,

> I took a look at the integration but I am still unsure if the original question was answered. I tried to run the todo example to see if it was using some kind of batching to avoid the N+1 issue and I don't think it does? I think it either misses some documentation on the topic or it is not done yet, can you comment on that @a8m.

The GraphQL documentation needs some improvement (I'll add more details to it), but as mentioned above, entgql uses [GraphQL field collection](http://spec.graphql.org/June2018/#sec-Field-Collection) and [eager loading](https://entgo.io/docs/eager-load/) for solving this problem. That means, if you query nodes and their edges, entgql automatically adds `With<E>` steps to your root query, and as a result, you'll only have constant number of queries to the database (and it works recursively).  

For example, given this query:

```graphql
query {
  users(first: 100) {
    edges {
      node {
        photos {
          link
        }
        posts {
          content
          comments {
            content
          }
        }
      }
    }
  }
}
```
You should see 1 query for getting the users, 1 for getting the photos, and another 2 for getting the posts and their comments (4 in total).

The logic I mentioned here works both for root queries/resolvers and for the node(s) API.

Regarding the todo-app example (in entgql), you can find the root resolvers in [this file](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/internal/todo/todo.resolvers.go#L44-L57), the generated edge resolvers in [this files](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/internal/todo/ent/edge.go#L21-L35), and the eager-loading binding [here](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/internal/todo/ent/collection.go) (the actual implementation for the eager-loading binding).

I OSS-ed entgql after we were running with it almost a year in production, so it's definitely in a production ready state. If you have specific troubles with it, or there's something concrete that doesn't work for you, let me know and I'll try to help.

**Comment by Sytten** [comment]
@a8m Thanks a lot for the answer, looks good to me! It is an interesting take on the N+1 problem for sure.

It leaves me wondering how privacy filter that requires two levels deep would work. Say if I have Tenant -> Group -> User and I want to make sure a user can only see other users in the tenant.
If I had a dataloader I would be confident that it would be a constant amount of requests, but here I think it would most likely need another DB request right?

**Comment by a8m** [comment]
> It leaves me wondering how privacy filter that requires two levels deep would work. Say if I have Tenant -> Group -> User and I want to make sure a user can only see other users in the tenant.

Can you elaborate how does your multi-tenancy model look like? I'm familiar with 3 different approaches and I implemented all the 3 with ent (and ent-privacy) - 1) A `tenant` column on each table 2) A `Tenant` node connected to all other nodes 3) Named-database per tenant.

The first 2 approached can be implemented with ent-privacy (i.e. `FilterRule`) which mutates the actually query (and doesn't execute additional query to the database) and the third one doesn't really need privacy layer for the tenant-filtering logic. 

> If I had a dataloader I would be confident that it would be a constant amount of requests, but here I think it would most likely need another DB request right?

I don't really understand what do you mean tbh. How does dataloader queries different from any other queries? You still need to  filter by tenant, right? Do I miss anything?

> Is it also possible to mix that with some custom resolvers for specific fields? I have some statistics that require custom SQL. I remember seeing someone mention thia need in another issue.

What is "that"? If you mean the edge-resolver, the answer is yes. You can override the default resolvers using gqlgen config (see, [entgo docs](https://entgo.io/docs/graphql/#usage-and-configuration)). 

If you want to share more about your use-case, I can try to help - I should be available on the [Slack](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) channel after the weekend. Feel free to ping me there.

**Comment by Sytten** [comment]
**Dataloaders**
So here is a more real world example of what I am talking about:
![SoWkIImgAStDuGejJYrIgCtNrSslLWX9pKlCA-7oBqg1YjNKmCG2Yl9JIfDBOA9W9LpE-RcvgNbmGQWQBeVKl1IWqG00](https://user-images.githubusercontent.com/2366731/103140434-825b2100-46b4-11eb-8c2f-e33035286737.png)

So if I was doing it with dataloaders:
- If I query orders and then ask for products, it is also fine because the dataloader already knows about the orders so it won't load them again to verify the permissions of products.
- If I query products I load the orders and then check the tenant_id on those and compare that to the viewer context. That does another SQL query to get the orders, it's fine since it will be grouped in a single query loading all orders at once.
- If I query comments, the dataloaders first query the products then query the orders. More work, but it is also fine because queries are grouped together so it only does 3 queries.

What would be the equivalent when using privacy filters?

**Custom SQL**
So I am building an observability SaaS for GraphQL, I am using TimescaleDB with some custom SQL functions that I need to call. I want to use ent for the rest of the system (Tenants, users, settings, api keys, etc.) but some fields will require SQL:
```graphql
{
  type(id: "dsadsa", filter: {start: "2020-12-01", end: "2020-12-31"}) {
    fields {
      latency { # This requires custom SQL
        timestamp
        value
      }
    }
  }
}
```
I am guessing that those fields will have a custom gqlgen resolvers anyway since they don't appear in the ent models.
Thanks a lot for the answers BTW, I feel the questions would help others too so feel free to put them in the doc.

**Comment by a8m** [comment]
Sorry for the delay - weekend mode 🏖️ 

> **Dataloaders**
> So here is a more real world example of what I am talking about:
> ![SoWkIImgAStDuGejJYrIgCtNrSslLWX9pKlCA-7oBqg1YjNKmCG2Yl9JIfDBOA9W9LpE-RcvgNbmGQWQBeVKl1IWqG00](https://user-images.githubusercontent.com/2366731/103140434-825b2100-46b4-11eb-8c2f-e33035286737.png)
> 
> So if I was doing it with dataloaders:
> 
> * If I query orders and then ask for products, it is also fine because the dataloader already knows about the orders so it won't load them again to verify the permissions of products.
> * If I query products I load the orders and then check the tenant_id on those and compare that to the viewer context. That does another SQL query to get the orders, it's fine since it will be grouped in a single query loading all orders at once.
> * If I query comments, the dataloaders first query the products then query the orders. More work, but it is also fine because queries are grouped together so it only does 3 queries.
> 
> What would be the equivalent when using privacy filters?

When you mention "query", do you mean GraphQL query? Does it mean that users can query comments and products directly in your example (i.e. root fields and resolvers)?

If you don't have an edge (or a field) from the `Tenant` type, you can add a privacy rule for filtering by an edge and there's no need for loading the associations for this. For example:

```go
// On product privacy filter rule.
q.Where(
    product.HasOrderWith(
        order.HasTenantWith(tenant.ID(tenant))
    ),
)
```

If you have an edge to the `Tenant` type, you can create an [ent.Mixin](https://entgo.io/docs/schema-mixin/) for holding the edge for the `Tenant` schema and the basic privacy policy for filtering by the tenant_id, and share it with all different schemas.

Of course, filtering by tenant_id is a super simple example for privacy policy. Our case is far more complicated than this, and it's working great for us - I hope to come up with some extensive example in the near future (it requires a lot of effort).  

Another last comment regarding this subject - we decided to tackle the "N+1 problem" for GraphQL in a different way than dataloader, because we found it much cleaner and simpler to use and understand. In the examples you mentioned, it looks like you use (or want to use) the dataloader also as a cache - to get objects that were already requested (right?) - if that's the case, I plan to provide support for multi-level cache in ent (request/session-level cache and a secondary-level cache like memcache/redis). I just prefer to separate the 2 problems. 

> So I am building an observability SaaS for GraphQL, I am using TimescaleDB with some custom SQL functions that I need to call. I want to use ent for the rest of the system (Tenants, users, settings, api keys, etc.) but some fields will require SQL:

Can you elaborate what type of custom SQL do you plan to use? You can extend ent using custom-templates

**Comment by Sytten** [comment]
> Sorry for the delay - weekend mode 🏖️

Not worries, this is helping me so much @a8m!

> > **Dataloaders**
> > So here is a more real world example of what I am talking about:
> > ![SoWkIImgAStDuGejJYrIgCtNrSslLWX9pKlCA-7oBqg1YjNKmCG2Yl9JIfDBOA9W9LpE-RcvgNbmGQWQBeVKl1IWqG00](https://user-images.githubusercontent.com/2366731/103140434-825b2100-46b4-11eb-8c2f-e33035286737.png)
> > So if I was doing it with dataloaders:
> > 
> > * If I query orders and then ask for products, it is also fine because the dataloader already knows about the orders so it won't load them again to verify the permissions of products.
> > * If I query products I load the orders and then check the tenant_id on those and compare that to the viewer context. That does another SQL query to get the orders, it's fine since it will be grouped in a single query loading all orders at once.
> > * If I query comments, the dataloaders first query the products then query the orders. More work, but it is also fine because queries are grouped together so it only does 3 queries.
> > 
> > What would be the equivalent when using privacy filters?
> 
> When you mention "query", do you mean GraphQL query? Does it mean that users can query comments and products directly in your example (i.e. root fields and resolvers)?

Exactly

> 
> If you don't have an edge (or a field) from the `Tenant` type, you can add a privacy rule for filtering by an edge and there's no need for loading the associations for this. For example:
> 
> ```go
> // On product privacy filter rule.
> q.Where(
>     product.HasOrderWith(
>         order.HasTenantWith(tenant.ID(tenant))
>     ),
> )
> ```

That makes sense, I didn't know you could nest the`where` like that.

> If you have an edge to the `Tenant` type, you can create an [ent.Mixin](https://entgo.io/docs/schema-mixin/) for holding the edge for the `Tenant` schema and the basic privacy policy for filtering by the tenant_id, and share it with all different schemas.

My point was more that if we have a privacy policy on the mixin, it will do unnecessary joins on the DB at each level if I am not mistaken (please correct me if I am wrong). This is fine but I guess you have to be aware of it. Say you start from products and you then load comments. The privacy filter on product will join with order to get the tenant ID. Then the privacy filter for comments will join on products and orders to get the tenant id. Where dataloaders you don't need to do that because it acts as a cache too for children graphql resolvers (and thus privacy filters). 

> Of course, filtering by tenant_id is a super simple example for privacy policy. Our case is far more complicated than this, and it's working great for us - I hope to come up with some extensive example in the near future (it requires a lot of effort).

That would be awesome, I think we already have a somewhat complex use case to start from here.

> Another last comment regarding this subject - we decided to tackle the "N+1 problem" for GraphQL in a different way than dataloader, because we found it much cleaner and simpler to use and understand. In the examples you mentioned, it looks like you use (or want to use) the dataloader also as a cache - to get objects that were already requested (right?) - if that's the case, I plan to provide support for multi-level cache in ent (request/session-level cache and a secondary-level cache like memcache/redis). I just prefer to separate the 2 problems.

Yes the dataloader caching is pretty important as I mentioned above because it prevents queries from children resolvers from having to do joins for privacy filtering. But an alternate solution is bad either, let's just make it easy to replace joins in privacy rules for better performances.

> 
> > So I am building an observability SaaS for GraphQL, I am using TimescaleDB with some custom SQL functions that I need to call. I want to use ent for the rest of the system (Tenants, users, settings, api keys, etc.) but some fields will require SQL:
> 
> Can you elaborate what type of custom SQL do you plan to use? You can extend ent using custom-templates

Mostly custom pl/pgsql functions that are defined by the extension. Mostly aggregations, counts and time filtering. I might write some custom template, but I feel it might call for raw SQL and a dataloader.
