### ISSUE TITLE
Feature Request: add Clear<E> for non-unique edges

### ISSUE THREAD

**Issue by vinicio** [facebook/ent#398]
I couldn't find another way to clear a M2M relationship besides quering the edge IDs before calling `...Update().RemoveMyEdgeIDs(ids...)`.

Is it possible to add something like `ClearMyEdge()`?

Thank you very much!

**Comment by a8m** [comment]
Hey @vinicio and thanks for opening this issue.

Let's keep it open to get more feedback from others.

**Comment by a8m** [comment]
I just want to add more context here - We've added the `Clear<E>` to unique edges, because it makes sense to just clear the edge instead of passing an id when there's only one option. 

In the current implementation, if you want to remove non-unique edges, you need to pass them explicitly using `Remove<E>` or `Remove<E>IDs`. 

I'm not sure how common is clear operation for non-unique edges, so as I commented before, let's see what others think about it.

**Comment by mrasong** [comment]
need clear too.
eg. 
an article has many tags, when we update the article , we first clear it's tag relation and then add new relations to it.
any other ways to better performance?

**Comment by napei** [comment]
Any idea when this will get tagged? Currently have a need for it when updating an entity and no easy way to just remove old non-unique M2M edges for that entity. 😄

**Comment by a8m** [comment]
Use `go get -u github.com/facebook/ent@master` atm please. I'll release a new version with a proper release note in the upcoming days.
