### ISSUE TITLE
Feature: Policy on Mixins

### ISSUE THREAD

**Issue by stffabi** [facebook/ent#465]
Hi 

Thanks for this awesome project. We are currently evaluating the Ent and would be happy to contribute some features which we would need and also think would be interesting for the community.
 
So here's our first one 😄 
What would you think about putting Policy also onto Mixins? This would allow us to implement some default policies based on fields that come with a mixin.

We would be happy to bring up a PR for this.

**Comment by a8m** [comment]
Hey @stffabi and thanks for proposing this feature. 
We actually discuss about it and we plan to add it to `Mixin` in the near future. 

It's not there at the moment because the [`Query`](https://godoc.org/github.com/facebookincubator/ent#Query) interface is currently empty and it's not possible to add generic code for mutating the different query builders. 

Once we finish the development of entql (a generic query language for ent), the different query builders will share the same interface and it will be possible to add write policies. Then, we'll add this to the Mixin interface.

Also note that `ent.Policy` is exported but is not documented because it's WIP and considered experimental. We'll change its status to stable once we feel comfortable with its design and implementation and we'll add proper documentation and examples for it as well.

**Comment by stffabi** [comment]
Hi @a8m thanks for your response.

Ah yes, that makes perfectly sense. There's no real win in having them added to `Mixin` without having entql. By the way entql sounds awesome 😄. I've also standup at some points because of a missing generic entql language. For e.g. to add additional predicates in a Mutator, for some sort of soft-delete mechanism.
I didn't think about it, because I've started some internal proof-of-concept where we generate Mixin based on the Schema Entities, e.g. `CardOurFeatureMixin`. We wanted to have a way to make some queries while in a `Mutator` but also needed this logic for several Entities not just one. And we didn't want to explicitly write this on every single Entity. So as a PoC we ended up generating Mixins which can then be added onto an Schema-Entity. 
For Bootstrapping a project you need to generate twice, but this is e.g. also needed if you wanna use `CardMutateFunc` in an Schema-Entity.
Well not as generic as having just one Mixin, but it solved our problem quite well 😄 . And as an extension to such a Mixin we now needed some Policies for filtering Queries. Which would also work because the Mixins get generated.

**Comment by a8m** [comment]
> For e.g. to add additional predicates in a Mutator, for some sort of soft-delete mechanism.

Exactly! that's one of the reason I decided to work on entql. Another reason is mentioned here - https://github.com/facebookincubator/ent/issues/277#issuecomment-622316098

**Comment by a8m** [comment]
The `Policy` option was added to `Mixin`. Please see [entgo.io/docs/privacy](https://entgo.io/docs/privacy/) for more information. 

Thanks for proposing this!
