### ISSUE TITLE
Proposal: Add method Clone on All RUD

### ISSUE THREAD

**Issue by deyforyou** [facebook/ent#668]
I mean if i set by default my predicate and i want to have a copy of this for my http handler in goroutines.
we have a method **Clone** on **schema_query**. Add method **Clone** for **schema_delete** and **schema_update**. No for **schema_create**

**Comment by a8m** [comment]
Hey @deyforyou and thanks for proposing this API.

I'm not sure I get the use case - you want to avoid copying the code that applying the predicate on the builders?

If you don't want to be blocked and want to add it to your project, use [external templates](https://entgo.io/docs/templates/) to generate this functionality for you.

**Comment by deyforyou** [comment]
_you want to avoid copying the code that applying the predicate on the builders?_ 
Yes so if i work with a server i can set default predicate or value on the builders.

sorry for the delay

**Comment by deyforyou** [comment]
Imagine each builder have an http handler func.
e.g: For UserCreate I do my first request I set the field "Name" to "deyforyou" and my second request I dont set. the value will stay always "deyforyou".
But it works only if i clone UserCreate in the handler func.

**Comment by a8m** [comment]
The reason we added the `Clone` method to the query builder was because it's possible to chain multiple builders as follows -  `e.QueryGroups().QueryPosts()...Clone()`. We found many cases that it's useful and reduced our code duplication. However, if we want to share the same setters for create/update builders we use [ent.Mutation](https://entgo.io/docs/crud/#mutation). Or, in cases like yours, we do stuff like this:

```go
func f() {
	// ...
	c1, c2 := baseUser(), baseUser()
	go saveUser(ctx, c1, "a8m")
	go saveUser(ctx, c2, "deyforyou")
}

func saveUser(ctx context.Context, c *ent.UserCreate, name string) {
	c.SetName(name).SaveX(ctx)
}

func baseUser() *ent.UserCreate {
	return client.User.Create().SetX(x).SetY(y).SetZ(z) // more setters.
}
```

Like I mentioned above, if you're blocked on this, you can use [external templates](https://entgo.io/docs/templates/) to add it to your project. But, I don't want to add it to the default codegen since this will make the generated code bigger for something that I didn't find (yet) super necessary and can be replaced with a few lines of code.

Thanks. Please let me know if you decided to use external templates and you need help with that.

**Comment by deyforyou** [comment]
Thank you. You are kind

**Comment by deyforyou** [comment]
And I use well external templates. But if you want to help me. it will be wonderful

**Comment by a8m** [comment]
> And I use well external templates. But if you want to help me. it will be wonderful

Sure thing, any specific issue? Did you start it already, or do you need help with writing the first template?

My suggestion is to start with adding a `Clone` method to the `<T>Mutation` object, and then, add another `Clone` method to the `<T>Create/Update` builder that will call the mutation clone method. Does it make sense?

**Comment by deyforyou** [comment]
I have already start. And I see now my error. But your suggestion is also good
