### ISSUE TITLE
When should we use this?

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#675]
Thanks for this work, this is great!!

I want to know if this library can be used for any general use case where [gorm](http://gorm.io/) solves or only in case of heavy usage of graph data. We have mix data use cases: we have graph data and also we have normal table data and we are planning to use postgres as storage so I am checking if this library can be leverage for both use cases.

Thanks in advance for your help.

**Comment by haoxinst** [comment]
Sometimes, this depends on the user's self.
For me, I just give a try on a small project, and that works fine.
We will move to ent totally when V1 is released.

https://github.com/facebook/ent/issues/46

We are using **GORM** currently.

**Comment by dilipkk-foyernet** [comment]
Thanks for your reply @haoxinst , that helps.

**Comment by a8m** [comment]
Hey @dilipkk-foyernet!
We use ent for small projects (2-3 entity types and a few relations) and we also use it in big projects with dozens of types and hundreds of edges - the size does not matter.

You can map any schema with ent. It doesn't matter if it's not a pure graph structure - see [schema relations guide](https://entgo.io/docs/schema-edges/#relationship).


About v1.0 - we didn't release it yet, because there are a few big features we want to add before we do it. However, we consider this project as **stable** as it's running in production (in multiple projects) more than a year.

Closing, but you can feel free to continue the discussion 😃

**Comment by dilipkk-foyernet** [comment]
Thanks Ariel, Is 1.0 expected to release by end of this year?
