### ISSUE TITLE
Question: How to use Custom Predicates

### ISSUE THREAD

**Issue by christie-zhao** [facebook/ent#693]
I am trying to add ancestor operator from Postgres ltree but the example in the document is unclear whether that is supported
```
pets := client.Pet.
    Query().
    Where(predicate.Pet(func(s *sql.Selector) {
        s.Where(sql.InInts(pet.OwnerColumn, 1, 2, 3))
    })).
    AllX(ctx)
```
Does this only support those already in `dialect/sql`?

**Comment by a8m** [comment]
Hey @christie-zhao!
For custom statically-typed predicates, please see our proposal for the [roadmap](https://github.com/facebook/ent/issues/277#issuecomment-622316098). It's actually under development at the moment.

If you want to use the SQL builder as mentioned in the doc, you can write to the builder directly, or use the new API I added:

```go
pets := client.User.
    Query().
    Where(predicate.User(func(s *sql.Selector) {
        s.Where(sql.P(func(b *sql.Builder) {
            b.Ident(user.EdgeColumn).WriteString(" <OP> ").Arg(value)
        }))
    })).
    AllX(ctx)
```

Closing, because there are actually 2 open issues for this case. Thanks 😃

**Comment by christie-zhao** [comment]
Thanks for the reply! I am still kinda confused since `sql.P()` takes no arguments. How can we pass it a func?

**Comment by a8m** [comment]
Please update to the latest version (master), and let me know if you have any issues with it. Thanks

**Comment by christie-zhao** [comment]
I did update 0.4.0 but `sql.P()` remains the same from before. What are the commands to update just to double check?

**Comment by a8m** [comment]
Update to master as follows:

```
go get -u github.com/facebook/ent@master
```

V0.4.1 will be released soon.
