### ISSUE TITLE
ent/examples/edgeindex/edgeindex.go error

### ISSUE THREAD

**Issue by peanut-cc** [facebook/ent#702]
in `ent/examples/edgeindex/edgeindex.go ` example

In the following code：
```
	_, err := client.Street.
		Create().
		SetName("ST").
		SetCity(tlv).
		Save(ctx)
	if err == nil {
		return fmt.Errorf("expecting creation to fail")
	}
```

Should be as follows：
```
	_, err := client.Street.
		Create().
		SetName("ST").
		SetCity(tlv).
		Save(ctx)
	if err != nil {
		return fmt.Errorf("expecting creation to fail")
	}
```
？？？

**Comment by a8m** [comment]
Hey @peanut-cc!

No, that's fine. See the comment above the code block:
![image](https://user-images.githubusercontent.com/7413593/91476104-2ff42a00-e8a5-11ea-981c-a1382f365bf0.png)

**Comment by peanut-cc** [comment]
ok

**Comment by a8m** [comment]
> ok

Did you understand why it's OK? as you can see, in the first block [here](https://github.com/facebook/ent/blob/master/examples/edgeindex/edgeindex.go#L43-L48), we're adding a street named "ST" to the city TLV, and since the street name must be unique under the city edge, the [next block](https://github.com/facebook/ent/blob/master/examples/edgeindex/edgeindex.go#L51-L55) should fail because they are duplicates.
