### ISSUE TITLE
Quick Introduction Feedback

### ISSUE THREAD

**Issue by jjr2527** [facebook/ent#705]
I don't have a lot of go experience so I may offer a different perspective on the documentation than those that have worked with go for some time now.  

Here are the notes I've taken up to "Create your first Entity" where I decided to call it a night after getting stuck.  I hope this can assist in augmenting the documentation for others.

notes
-------------------
![image](https://user-images.githubusercontent.com/135577/91519583-a5b5c100-e8b8-11ea-987c-027e9ba299a2.png)

**Comment by a8m** [comment]
Hey @jjr2527 and thanks for the feedback! The best way to discuss about documentation improvement is by suggesting a **specific** change using a PR.

I'd be happy to see it get better (and more user friendly), because I'm the one who created these docs (took me ages btw).

Closing, but like I mentioned above, if you have specific change that you think can help others in the future, propose it using a PR and we can discuss about it! Thanks 😃
