### ISSUE TITLE
How to add custom functions?

### ISSUE THREAD

**Issue by christie-zhao** [facebook/ent#708]
Hi! Thanks for all the patience and explanations! I am implementing `ltree` for Postgres and I have been struggling for days on how to implement custom functions like `subpath` or `nlevel`. I don't know how to make them interact with the ent builder and selector since I can't modify ent files. Any advice?

**Comment by a8m** [comment]
Hey @christie-zhao and it's great to see you here again.

> I have been struggling for days on how to implement custom functions like subpath or nlevel. I don't know how to make them interact with the ent builder and selector since I can't modify ent files. Any advice?

Can you give more context about it? What are you trying to do, or something I can reproduce/run to help with it.

Are you talking about adding them to the generated predicates (using [external templates](https://entgo.io/docs/templates/))?

**Comment by christie-zhao** [comment]
I am trying to use external templates for that. For example, I want to implement `nlevel` function to count number of labels in ltree path and returns a number. Then, I would like to use it like `client.query().where(predicates).nlevel(path).all()` or `client.query().select(...).nlevel(path)` or some sort. It works very similar to `count` function.

**Comment by a8m** [comment]
Are you trying to run a query like this?
```sql
SELECT nlevel("<Column>") FROM "test" WHERE <Predicate>;
```
Or this:
```sql
SELECT * FROM "test" WHERE nlevel("<Column>") > $1;
```

Can you write here please an example of your table (with a few rows), and the expected output (SQL rows and Go objects)? Thanks

**Comment by christie-zhao** [comment]
Hi I didn't realize I can do that but that solves the problem. Now I have another problem...Thank you so much for all the help!![issue-571](https://github.com/facebook/ent/issues/571)

**Comment by a8m** [comment]
Hey @christie-zhao,

> Actually I didn't figure it out... 

Can you elaborate what it's working for you? 

> However, I want to have this function in the custom template so I can use it wherever.

If you want to add code using custom templates see the [external-templates docs](https://entgo.io/docs/templates/), or see examples in [integration tests](https://github.com/facebook/ent/blob/fd0a7f9/entc/integration/template/ent/generate.go) and [examples](https://github.com/facebook/ent/blob/5450481/examples/entcpkg/ent/entc.go) directories.

**Comment by christie-zhao** [comment]
So now I did `client.Tree.Query().Select("Nlevel(path)").Ints(ctx)` and it is giving me an error because the raw query representation of this is `SELECT tree.Nlevel(path) FROM tree`. `Nlevel(path)` is a function but not a column so `tree.Nlevel(path)` doesn't make sense

**Comment by a8m** [comment]
Regarding the first issue - The `Select(field string, fields ...string)` function accepts fields and not raw strings. It won't work this way.

The second case caused by a misconfigured driver - you need to configure the dialect for the builder (see examples in generated code). For example:

```go
builder := sql.Dialect(nt.driver.Dialect())
table := builder.Table(tree.Table)
selector := builder.Select(...).From(table).Where(...)
query, args := selector.Query()
```

**Comment by christie-zhao** [comment]
Yeah this would be useful. However `nlevel` doesn't only work with the column, it also works with any tree path. For example, I can do `select nlevel('A') from tree` and it would give me 1 as a result.

Also how can I integrate this in the template? as I don't have permission to add this in the treequery file?

**Comment by christie-zhao** [comment]
This solved it! I didn't know I can get TreeQuery outside! You are so helpful and awesome!!! 💯

**Comment by christie-zhao** [comment]
Just a small question, How do you prevent sql injection when using `fmt.Sprintf`?

**Comment by jaredallard** [comment]
Just wanted to add a 👍 here, thanks a bunch for being so responsive @a8m. I work with @christie-zhao and you've helped us a bunch ❤️

**Comment by a8m** [comment]
Thanks for the kind words @jaredallard and @christie-zhao 😃 

> This solved it! I didn't know I can get TreeQuery outside. You are so helpful and awesome!!! 💯

You can add methods to the query builder from another file, and external-templates can help you to generate those methods. If you're struggling with it, create a temporary repository with a reproducible example (and some schema) and I'll create a PR for helping you with it.


> Just a small question, How do you prevent sql injection when using fmt.Sprintf?

In general, we use parametrized statement/queries for executing the SQL queries, so you don't need to worry if you're passing untrusted user-inputs to the builtin builder methods (like predicates, or when inserting data). You can see the generated SQL statement when calling `client.Debug()`.

However, the select expression is part of the SQL syntax and can't be passed using placeholders (`SELECT ? FROM ...`) - this is why we're accepting only fields for selection, and users should use the generated constants for passing those fields. We can enforce this, but injections are not expected to be on the SQL syntax level. There's a good discussion in the SQLAlchemy issue tracker - we can add a check for enforcing this (I'll do it).

If you're adding new functionalities using external-templates, you should verify user-inputs or use placeholders where it's possible.

Regarding the question about `sql.Selector` in #742 - the query builders in `dialect/sql` are used for providing a statically-typed API for the generated ent code. They don't do syntax check nor escaping or other magic. It's considered an "internal" package of ent, and it's exposed only because the generated packages need them. I'll add it in doc comment.

**Comment by christie-zhao** [comment]
If I'm understanding correctly, in the example you had above on Nlevel, we need to do more input sanitization on the parameter column? 'selector.C()' only formats it but it doesn't prevent injection?

**Comment by a8m** [comment]
> If I'm understanding correctly, in the example you had above on Nlevel, we need to do more input sanitization on the parameter column?

Yes. Usually, I'll recommend to not pass untrusted data to methods that don't accept placeholders - define constants and use them instead.

We can consider adding the sanitization option to the sql helpers we have under `dialect/sql` - but that's a different discussion.
