### ISSUE TITLE
Feature Request: Order for Enum-Columns

### ISSUE THREAD

**Issue by jojomi** [facebook/ent#713]
I like this project a lot, but hit a road block when I was using an `enum` field and wanted to sort it like this:

```
data, err := client.ZTask.Query().Order(ent.Desc(ztask.FieldPriority))
```

The field is defined like this:

```
...
		field.Enum("priority").
			Values("low", "middle", "high").
			Default("middle").
			Optional(),
...
```

Intuitively I thought the field might be modeled as integer and mapped to the strings (in the order I gave them when defining the field), but it seems the actual strings are used and thus **I get alphabetical order** when sorting.

Is there a way to keep my "order" instead of using an integer field and mapping the values myself? I am using the SQLite backend.

Thank you for any pointer to the right direction and this great tool!

**Comment by a8m** [comment]
Hey @jojomi and thanks for the kind words!

> but it seems the actual strings are used and thus I get alphabetical order when sorting.

This was changed lately and I think we're going to revert it. However, in SQLite (and PostgreSQL), we use `varchar` for storing the enum values and only MySQL supports the index-based ordering - because it's the only driver that supports the builtin enum type.

I think, the ideal solution is to add support for "numeric-enums" - it's not really supported by the underlying database, but it works better for some cases (like yours).

My suggestion for you, is to configure something as follows, and maybe migrate it to the "numeric enum" in the future:
```go
// Fields of the Task.
func (Task) Fields() []ent.Field {
	return []ent.Field{
		field.Int("priority").
			GoType(Priority(0)).
			Default(int(PriorityMid)).
			Validate(func(i int) error {
				return Priority(i).Validate()
			}),
		// More fields.
	}
}

type Priority int

const (
	PriorityLow Priority = iota
	PriorityMid
	PriorityHigh
)

func (p Priority) String() string {
	s := "unknown"
	switch p {
	case PriorityLow:
		s = "low"
	case PriorityMid:
		s = "mid"
	case PriorityHigh:
		s = "high"
	}
	return s
}

func (p Priority) Validate() error {
	switch p {
	case PriorityLow, PriorityMid, PriorityHigh:
		return nil
	default:
		return fmt.Errorf("invalid priority value: %v", p)
	}
}
 ```

See the usage for this example [here](https://github.com/facebook/ent/blob/673a049/entc/integration/type_test.go#L134-L151).

**Comment by a8m** [comment]
> This was changed lately and I think we're going to revert it.

Change was reverted and we'll be added in v0.4.1

Closing, thanks!

**Comment by syssam** [comment]
@a8m any update for "numeric enum"?

**Comment by a8m** [comment]
Hey @syssam, please see the suggested example https://github.com/ent/ent/issues/713#issuecomment-683403919

**Comment by syssam** [comment]
@a8m just idea, use this statement `field.Enum("priority").Values("low", "middle", "high").Default("middle").Optional(),`, but we can implement `func (p Priority) Value() (driver.Value, error)` and `func (p *Priority) Scan(val interface{}) error {`

**Comment by syssam** [comment]
Hey, @a8m any feedback?
