### ISSUE TITLE
Question: how should I deal with table partition?

### ISSUE THREAD

**Issue by zjttbkd** [facebook/ent#768]
e.g: if we divide the table into 100 according to ID, how should I specify the table name

**Comment by a8m** [comment]
Hey @zjttbkd!
Unfortunately, we don't support table partitioning atm, and it won't be supported in V1. 
We have discussions about adding this functionality, but that's not an easy task, because the current implementation expect that all data reside in the same database. 

Closing, but we can open it as a proposal after V1.
