### ISSUE TITLE
question: query clone loss eager load and gen method name

### ISSUE THREAD

**Issue by maxiloEmmmm** [facebook/ent#878]
## Q1
```go
query := client.X.Query()
query.WithX()

queryClone  = query.Clone()
// queryClone.withX is nil
```

## Q2
```go
field.String("url")

// gen
setURL not setUrl
```
Is this deliberately designed?

**Comment by a8m** [comment]
Hey @maxiloEmmmm and welcome again 😃 

Regarding the first question/issue, we should fix it. If you want to contribute this change, you can start from changing the [`generated Clone`](https://github.com/facebook/ent/blob/master/entc/gen/template/builder/query.tmpl#L256-L268) method (see the naming convention in [line 31](https://github.com/facebook/ent/blob/master/entc/gen/template/builder/query.tmpl#L31-L36)). 

Regarding the second question - Yes, this is intentional. See the [Go CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms) for more info (e.g. [net/url.URL](https://golang.org/pkg/net/url/#URL)).

**Comment by maxiloEmmmm** [comment]
@a8m 
Q2:
i want use words list to reflect set method for https://github.com/maxiloEmmmm/go-web/blob/5b44d6b89a21ba71150853193cff81c5edaf5ee5/contact/curd.go#L225

### words list like this:
- https://github.com/golang/lint/blob/738671d3881b9731cc63024d5d88cf28db875626/lint.go#L770
- https://github.com/facebook/ent/blob/17abe2d60fdfa91639369fb2d0f5cb7ba4950ec1/entc/gen/func.go#L271

if words list not change in the future, i want copy 
Will it change in the future?

**Comment by maxiloEmmmm** [comment]
@a8m 
Q2:
i want use words list to reflect set method for https://github.com/maxiloEmmmm/go-web/blob/5b44d6b89a21ba71150853193cff81c5edaf5ee5/contact/curd.go#L225

### words list like this:
- https://github.com/golang/lint/blob/738671d3881b9731cc63024d5d88cf28db875626/lint.go#L770
- https://github.com/facebook/ent/blob/17abe2d60fdfa91639369fb2d0f5cb7ba4950ec1/entc/gen/func.go#L271

if words list not change in the future, i want copy 
Will it change in the future?

**Comment by a8m** [comment]
> if words list not change in the future, i want copy
Will it change in the future?

No. However, we may add more words to it in the future. I'll keep you updated if that happens.

**Comment by maxiloEmmmm** [comment]
@a8m ok

**Comment by maxiloEmmmm** [comment]
@a8m no time for pr recently, tks
