### ISSUE TITLE
Nullable Foreign Key UUID

### ISSUE THREAD

**Issue by tommynurwantoro** [facebook/ent#906]
Hello,

Why can't we create schema foreign key with type nullable UUID?
Here is my sample code:
```go
func (Bucket) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.UUID("parent_bucket_id", uuid.UUID{}).Optional(),
		field.String("name").MaxLen(100).NotEmpty(),
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
		field.Time("deleted_at").Optional(),
	}
}
```
parent_bucket_id is the foreign key.
I already use Optional() in parent_bucket_id, but it didn't work, the field is still NOT NULLABLE. Is it expected?

Thanks.

**Comment by a8m** [comment]
Hey @tommynurwantoro, in order to define relationships (and their foreign-key), you should use the [Edges](https://entgo.io/docs/schema-edges/) option. If we take your example, it will look as follows:

```go
// Edges of the Node.
func (Bucket) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("children", Bucket.Type).
            From("parent").
            Unique(),
    }
}
```

See the [O2M example](https://entgo.io/docs/schema-edges/#o2m-same-type) in the doc.

Closing, but feel free to continue the discussion if you still need help.
