### ISSUE TITLE
question: How to aggregate without group

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#950]
Is there a way to query the graph like this sql-query would:
```sql
select sum(balance) from accounts where user_id = 1
```
So far i need to create a `GroupBy("id")` first, which seems a little weird to me.

**Comment by a8m** [comment]
Hey @masseelch and sorry for the delayed response.
Please see https://github.com/facebook/ent/issues/708#issuecomment-689070774 as a reference example for your question.

If you think a new API needs to be provided by ent (or can be improved), feel free to open a proposal for it.

Also, since you're not new here 😉, I appreciate if you can add your company to the [community users page](https://github.com/facebook/ent/wiki/ent-users) if you're using it in your product. Thanks!

**Comment by masseelch** [comment]
For now my solution is ugly but working and the the data is small enough so I do not run into performance issues. 

I am using ent to learn go, mostly in my free time. The moment my company starts using ent I will add it.

**Comment by a8m** [comment]
Wonderful, thanks.

**Comment by a8m** [comment]
Hey! I just want to update you that the aggregation API was simplified, and you can read about it here https://twitter.com/entgo_io/status/1584091539479080960 and https://entgo.io/docs/aggregate.

Also, here's a small example:

```go
// Aggregate one field.
sum, err := client.Order.Query().
    Aggregate(
        ent.Sum(order.FieldPrice),
    ).
    Int(ctx)

// Aggregate multiple fields.
var v []struct {
    Sum, Min, Max, Count int
}
err := a8m.QueryOrders().
    Aggregate(
        ent.Sum(order.FieldPrice),
        ent.Min(order.FieldPrice),
        ent.Max(order.FieldPrice),
        ent.Count(),
    ).
    Scan(ctx, &v)
```
