### ISSUE TITLE
Question: How to create an edge to itself?

### ISSUE THREAD

**Issue by hm0** [facebook/ent#979]
I have a use case where I must have a table with the following structure:

Table "Group"=(Id, name, value, parent)  // the "parent" column references an Id from another row within the same table Group.

hmo@jupiter ruler % go generate ./ent
entc/gen: resolve "Group" relations: edge "groups" is missing for inverse edge: Group.groups

**Comment by napei** [comment]
https://entgo.io/docs/schema-edges/#o2o-same-type
https://entgo.io/docs/schema-edges/#o2m-same-type
https://entgo.io/docs/schema-edges/#m2m-same-type

What you want is a same-type relationship. I gather it's probably a o2m relation as a group could be a parent of many groups?

Regardless, You may want something like this.

```go
// Group holds the schema definition for the Group entity.
type Group struct {
	ent.Schema
}

// Fields of the Group.
func (Group) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("name"),
		field.String("value"),
		field.Int("parent"),
	}
}

// Edges of the Group.
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("group_children", Group.Type),
		edge.From("group_parent", Group.Type).Ref("group_children").Unique(),
	}
}
```

Edges must have a from and to even if they are self-referential. Because if you have a group, you would want to know it's children as well as knowing its parent.

**Comment by a8m** [comment]
Thanks @napei for the support. Maybe one comment here, as mentioned in [docs](https://entgo.io/docs/schema-edges/#o2m-same-type/) you can define this <i>O2M (same type)</i> relationship as follows:
```go
// Edges of the Node.
func (Group) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("children", Group.Type).
            From("parent").
            Unique(),
    }
}
```

@hm0 please let us know if you need further help with this.

**Comment by hm0** [comment]
Hello, 
Thanks a lot @napei  and @a8m . That worked.
